stages:
  model_training:
    cmd: python src/model_training.py
    deps:
    - dataset/feature_engineering
    - src/model_training.py
    params:
    - model_training.test_size
    - model_training.random_state
    - model_training.lr
    outs:
    - model/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - model/model.pkl
    - src/model_evaluation.py
    params:
    - model_evaluation.test_size
    - model_evaluation.random_state
    outs:
    - model_reports/metrics.json

metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
params:
- dvclive/params.yaml
