data_ingestion:
  data_path : 'https://raw.githubusercontent.com/Codebreaker42/house-price-predictor/refs/heads/master/Pune_property_data.csv'
  # data_path: 'Pune_property_data.csv'

model_training:
  test_size : .15
  random_state : 42
  lr : .4

model_evaluation:
  test_size : .15
  random_state : 42